# Generated by Django 5.1.1 on 2024-09-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("mobileNo", models.IntegerField()),
                ("dob", models.DateField(blank=True, null=True)),
                ("pic", models.ImageField(blank=True, null=True, upload_to="")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Debit Card", "Debit Card"),
                            ("Credit Card", "Credit Card"),
                            ("UPI", "Pay UPI"),
                        ],
                        max_length=100,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.student",
                    ),
                ),
            ],
        ),
    ]
