# Generated by Django 5.1.1 on 2024-09-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="student",
            field=models.ManyToManyField(blank=True, null=True, to="Core.student"),
        ),
    ]
