# Generated by Django 5.0.7 on 2024-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("mobileNo", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
                ("salary", models.FloatField()),
            ],
        ),
    ]
